development:
  access_key_id: AKIAIPIELFZCFEWF7UMQ
  secret_access_key: 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

production:
  access_key_id: AKIAIPIELFZCFEWF7UMQ
  secret_access_key: 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